services:
  catalogo:
    build: ./catalogo
    container_name: catalogo_app
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=app_db
    networks:
      - rede-interna
    depends_on:
      - auth-service
      - db

  auth-service:
    build: ./auth-service
    container_name: auth_app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=app_db
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USER=9bd07c441f6778
      - SMTP_PASS=e76d9b0b30bfe3
    networks:
      - rede-interna
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mariadb_app
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - rede-interna

networks:
  rede-interna:
    driver: bridge

volumes:
  db_data: